spring.application.name=sid
spring.config.import=optional:file:.env[.properties]

# Credentials Configuration
spring.cloud.aws.credentials.access-key=${AWS_ACCESS_KEY_ID}
spring.cloud.aws.credentials.secret-key=${AWS_SECRET_ACCESS_KEY}

# Region Configuration
spring.cloud.aws.region.static=${AWS_REGION}
spring.cloud.aws.region.auto=false